apiVersion: apps/v1

kind: Service
metadata:
  name: terminal-ssh-service
  namespace: development
spec:
  selector:
    app: terminal
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
  type: ClusterIP

---
kind: ReplicaSet
metadata:
  name: terminal
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terminal
  template:
    metadata:
      labels:
        app: terminal
    spec:
      containers:
      - name: terminal
        image: <your-docker-image> # Replace with the actual image name
        volumeMounts:
        - name: nginx-volume
          mountPath: /mnt/nginx
        - name: nvim-volume
          mountPath: /mnt/nvim
      volumes:
      - name: nginx-volume
        hostPath:
          path: /path/on/host/machine/nginx # Replace with the actual path
          type: Directory
      - name: nvim-volume
        hostPath:
          path: /path/on/host/machine/nvim # Replace with the actual path
          type: Directory
