FROM ubuntu:kinetic-20230126

RUN apt-get -y update && apt-get -y upgrade

RUN apt-get -y install software-properties-common 
RUN apt-get -y install apt-transport-https ca-certificates
RUN apt-get -y install python3 python3-pip
RUN apt-get -y install git curl vim zsh unzip jq

RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN apt-get -y upgrade -y && apt-get -y autoremove -y && apt-get -y clean -y

ENV PATH="$PATH:/root/.local/bin"

WORKDIR /work