FROM ubuntu:23.04

RUN apt-get -y update && apt-get -y upgrade

RUN apt-get -y install software-properties-common 
RUN apt-get -y install apt-transport-https ca-certificates
RUN apt-get -y install git curl vim zsh  

RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

RUN apt-get -y upgrade -y && apt-get -y autoremove -y && apt-get -y clean -y

WORKDIR /work